name: Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: self-hosted
        steps:
            - name: Pull changes
              run: git -C /home/friends/map pull